Khaaz/AxonCore

src/AxonClient.js, src/Conf/templateConf.json, src/Database/JsonService.js, src/Database/MongoService.js, src/Database/index.js, src/Errors/AxonCommandError.js, src/Errors/AxonError.js, src/Loggers/ChalkLogger.js, src/Loggers/DefLogger.js, src/Loggers/SignaleLogger.js, src/Loggers/index.js, src/Structures/Base.js, src/Structures/Command.js, src/Structures/EnsureInterface.js, src/Structures/Event.js, src/Structures/EventManager.js, src/Structures/Module.js, src/Utility/AxonUtils.js, src/Utility/Collection.js, src/Utility/Utils.js
I would like to thank myself for existing and not completely giving up midway.
I would also like to note that my brain just gave up deciphering what Khaaz wrote after AxonClient.js
Needs to be checked for typos and misinformation because nobody's perfect.
=> Updated the documentation

esmExport.js, example/src/modules/Core/commands/Wave.js, example/src/modules/Core/commands/index.js, example/src/modules/Private/commands/Eval.js, src/Utility/Prompt.js
Added Prompt.js, a class that works as Prompt from the Klasa handler for djs,
Example command for prompt: wave
=> Added Prompt

esmExport.js, example/src/modules/Private/commands/Collect.js, example/src/modules/Private/commands/index.js, src/Utility/MessageCollector.js
Basically a broader and more useful Prompt.
=> Added MessageCollector

index.d.ts, package.json, yarn.lock
V2 Typings base, with all previous typings updated to V2. Further typings will need to be added to cover the entire library.
*I would highly suggest using these typings to fix the JSDoc*
Oh, I updated the typescript package too.
=> Base v2 typings

src/Database/Schemas/MongoSchemaGenerator.js, src/Database/Schemas/SchemaGenerator.js
This PR is basic implementation of a AutoSchema and is still a work in progress.
=> Add Basic Auto Schema Generation Implementation

examples/djs/src/configs/customConfig.json, examples/djs/src/modules/Core/listeners/MessageCreateLog.js, examples/djs/src/modules/Core/listeners/MessageCreateMod.js, examples/eris/src/Bot.js, examples/eris/src/configs/customConfig.json, examples/eris/src/modules/Core/listeners/MessageCreateLog.js, examples/eris/src/modules/Core/listeners/MessageCreateMod.js, index.d.ts, src/AxonClient.js, src/AxonOptions.js, src/Database/DBLessService.js, src/Database/InMemoryProvider.js, src/Database/index.js, src/Libraries/index.js, src/Utility/Constants/AxonEnums.js
Fixed things related to axonOptions, the library selector, added Database-less function and fixed up some more bugs that prevented either the database or the examples from properly functioning.
This fixed bugs related to options, databases, and the library after adding the ability for AxonCore to run without any sort of database.
Database-less is now the default database but JSON is the failover in case someone tries to use a database and it does not work.
=> Add databaseless + bug fix

index.d.ts
Fixes a bug where custom named staff groups will error on Typescript build
=> docs/typings(index.d.ts): Allow name of any group of AxonStaff

src/Libraries/eris/handlers/InviteCreateHandler.js, src/Libraries/eris/handlers/InviteDeleteHandler.js, src/Libraries/eris/handlers/index.js, src/Libraries/eris/lib/ErisEnums.js
This PR adds upcoming InviteCreate and InviteDelete events support to the framework.
Ref: abalabahaha/eris#625
Ref discord-api: discordapp/discord-api-docs#1309
=> feat(Libraries/eris): InviteCreate + InviteDelete events

src/Libraries/discordjs/handlers/GuildMembersChunkHandler.js, src/Libraries/discordjs/handlers/InviteCreateHandler.js, src/Libraries/discordjs/handlers/InviteDeleteHandler.js, src/Libraries/discordjs/handlers/ShardDisconnectHandler.js, src/Libraries/discordjs/handlers/ShardResumeHandler.js, src/Libraries/discordjs/handlers/index.js, src/Libraries/discordjs/lib/DjsEnums.js
This PR add supports for InviteCreate and InviteDelete events.
This also cleanup some events names.
Ref: discordjs/discord.js#3720
Discord: discordapp/discord-api-docs#1309
=> feat(Libraries/djs): InviteCreate + InviteDelete events

src/Libraries/discordjs/handlers/MessageReactionRemoveEmojiHandler.js, src/Libraries/discordjs/handlers/index.js, src/Libraries/discordjs/lib/DjsEnums.js
This PR add support for the new MessageReactionRemoveEmoji event to the framework.
Ref: discordjs/discord.js#3723
Discord: discordapp/discord-api-docs#1309
=> feat(Libraries/djs): MessageReactionRemoveEmoji event

src/Libraries/eris/handlers/MessageReactionRemoveEmojiHandler.js, src/Libraries/eris/handlers/index.js, src/Libraries/eris/lib/ErisEnums.js
This PR brings support to the new MessageReactionRemoveEmoji event to the framework.
Ref: abalabahaha/eris#631
Discord: discordapp/discord-api-docs#1309
=> feat(Libraries/eris): MessageReactionRemoveEmoji event

src/Database/MongoProvider.js
Mongoose use lean for everything apart from getGuildSchema to increase speed significantly - [see here](https://canary.discordapp.com/channels/203039963636301824/347816470589341706/703737585738186843)
=> refactor/perf: Mongoose improvements

src/Database/MongoProvider.js, types/Database/Mongo/AxonSchema.ts, types/Database/Mongo/GuildSchema.ts, types/Database/MongoProvider.ts, types/index.ts
- Add GuildDocument and AxonDocument typings
- Fix AxonSchema and GuildSchema not typed as a model but as a document instead
=> fix/docs/typings: Add Guild/AxonDocument typings, making stuff clearer

src/Database/MongoProvider.js, types/Database/MongoProvider.ts
fetchGuildSchema => fetchGuildDocument
Originally misleading name
=> breaking(MongoProvider): Rename method

src/AxonClient.js, src/Database/InMemoryProvider.js, src/Database/JsonProvider.js, src/Database/MongoProvider.js, src/Database/index.js, types/Database/ADBProvider.ts, types/Database/InMemoryProvider.ts, types/Database/JsonProvider.ts, types/Database/MongoProvider.ts
In preparation for a bigger Axonoptions extensions rework, plus fixes custom DB Providers not being inited.
=> refactor/fix: Move DB init to AxonClient

src/AxonOptions.js, types/Libraries/discordjs/Channel.ts, types/misc/interfaces.ts
Add ts-ignore to fix build errors in djs/Channel and match type and JSDoc in AxonOptionsExtensions
=> docs/fix: Corrections

src/AxonClient.js, src/Core/Stores/GuildConfigCache.js, src/Database/ADBProvider.js, src/Database/InMemoryProvider.js, src/Database/JsonProvider.js, src/Database/MongoProvider.js, types/AxonClient.ts, types/Database/ADBProvider.ts, types/Database/InMemoryProvider.ts, types/Database/JsonProvider.ts, types/Database/MongoProvider.ts
Adds support for custom AxonConfigs and GuildConfigs that were previously missing, this should make accessing axonConfig and guildConfig show the user's custom config class.
=> feat: Add support for custom Axon/GuildConfigs

src/AxonClient.js, src/Core/Loaders/ClientInitialiser.js, src/Database/ADBProvider.js, src/Database/InMemoryProvider.js, src/Database/JsonProvider.js, src/Database/MongoProvider.js, src/Database/index.js, src/Libraries/index.js, types/AxonClient.ts, types/Core/Loaders/ClientInitialiser.ts, types/Database/ADBProvider.ts, types/Database/DBSelector.ts, types/Database/JsonProvider.ts, types/Database/MongoProvider.ts, types/index.ts, types/misc/interfaces.ts
Include uninstantiated classes from AxonOptions.extensions in AxonClient for initialisation
=> refactor: Extensions rework

package.json, scripts/typings.js, yarn.lock
Adds absolutely nothing. But bumps doc-gen version for a new update and fixes to scripts
=> misc: various module updates

src/Utility/Utils.js, types/Utility/Utils.ts
Fixes string splitter when the EOS isn't a newline character, also adds custom length split
=> Fix string split regex and improvements

src/Utility/AxonUtils.js
AxonUtils.isBotStaff no longer errors due to a loop issue and uses includes over find.
=> Fix AxonUtils.isBotStaff

package.json, types/AxonClient.ts, types/Core/Base.ts, types/Core/Command/CommandEnvironment.ts, types/Langs/MessageManager.ts, types/Langs/MessageParser.ts, types/Langs/TranslationManager.ts, types/Libraries/definitions/Channel.ts, types/Libraries/definitions/Message.ts, types/Libraries/definitions/types.ts, types/Libraries/discordjs/Channel.ts, types/Libraries/discordjs/LibraryInterface.ts, types/Libraries/discordjs/types.ts, types/Libraries/eris/Channel.ts, types/Libraries/eris/LibraryInterface.ts, types/Libraries/eris/Message.ts, types/Libraries/eris/types.ts, types/Utility/AxonUtils.ts, types/Utility/Discord/Collectors/MessageCollector.ts, types/Utility/Discord/Prompt.ts, types/index.ts, types/misc/interfaces.ts, yarn.lock
Improvements to TS Docs - Generics added to LibMessage and added missing/improved MessageManager typings
Please note I have not tested this on D.JS and unsure if my changes will break anything. Has been tested on Eris.
Also updated TypeScript version
=> typings/chore: TypeScript documentation and typings improvements

src/Libraries/discordjs/DjsInterface.js, src/Libraries/eris/ErisInterface.js, src/Utility/Discord/Collectors/ReactionCollector.js, types/Libraries/default.ts, types/Libraries/definitions/types.ts, types/Libraries/discordjs.ts, types/Libraries/discordjs/types.ts, types/Libraries/eris.ts, types/Libraries/eris/types.ts, types/Libraries/index.ts, types/Utility/Discord/Collectors/ReactionCollector.ts, types/index.ts, types/misc/interfaces.ts
Adds Reaction Collector - this is a copy of Message Collector but modified to accept reactions instead of messages
=> feat: Add Reaction Collector

src/AxonClient.js, src/Core/Command/Command.js, src/Core/Command/CommandPermissions.js, src/Utility/Discord/Prompt.js
Fixing the permission issue in DM. 
Checking if staff is needed and if user if included in.
- [  ] This PR have been tested and is ready to be merged.
=> Fixing permissions in DM for bot owners

src/Langs/TranslationManager.js
When using this.l.FUNCTION(args, lang), FUNCTION will now return the value from the default lang in case the value does not exist in selected lang.
=> Returns the key's value from default language.
